#include "AdjectiveNoun.h"

#include <QRandomGenerator>

// Thank you to a bunch of friends for coming up with a pile of these, fun exercise ;)
class AdjectiveNounPrivate {
public:
    AdjectiveNounPrivate() {}
    ~AdjectiveNounPrivate() {}
    const QStringList adjectives{
        QLatin1String{"Abrasive"},
        QLatin1String{"Abrupt"},
        QLatin1String{"Action"},
        QLatin1String{"Advanced"},
        QLatin1String{"Airy"},
        QLatin1String{"Ambient"},
        QLatin1String{"Angry"},
        QLatin1String{"Arpegiated"},
        QLatin1String{"Arresting"},
        QLatin1String{"Arythmic"},
        QLatin1String{"Atonal"},
        QLatin1String{"Balanced"},
        QLatin1String{"Banging"},
        QLatin1String{"Basic"},
        QLatin1String{"Bellowing"},
        QLatin1String{"Big"},
        QLatin1String{"Billowing"},
        QLatin1String{"Bittersweet"},
        QLatin1String{"Bleak"},
        QLatin1String{"Bloated"},
        QLatin1String{"Blooming"},
        QLatin1String{"Bluesy"},
        QLatin1String{"Blunt"},
        QLatin1String{"Boosted"},
        QLatin1String{"Brassy"},
        QLatin1String{"Brave"},
        QLatin1String{"Bright"},
        QLatin1String{"Broken"},
        QLatin1String{"Brutal"},
        QLatin1String{"Bubbly"},
        QLatin1String{"Cacophonous"},
        QLatin1String{"Calm"},
        QLatin1String{"Catchy"},
        QLatin1String{"Cathartic"},
        QLatin1String{"Casual"},
        QLatin1String{"Catastrophic"},
        QLatin1String{"Chilling"},
        QLatin1String{"Chromatic"},
        QLatin1String{"Clever"},
        QLatin1String{"Cluttered"},
        QLatin1String{"Coalescing"},
        QLatin1String{"Cold"},
        QLatin1String{"Conspiratorial"},
        QLatin1String{"Creeping"},
        QLatin1String{"Critical"},
        QLatin1String{"Crowing"},
        QLatin1String{"Crunchy"},
        QLatin1String{"Dastardly"},
        QLatin1String{"Dank"},
        QLatin1String{"Dark"},
        QLatin1String{"Declining"},
        QLatin1String{"Deep"},
        QLatin1String{"Dirty"},
        QLatin1String{"Discordant"},
        QLatin1String{"Dissonant"},
        QLatin1String{"Distinct"},
        QLatin1String{"Dizzy"},
        QLatin1String{"Doubtful"},
        QLatin1String{"Dragging"},
        QLatin1String{"Dripping"},
        QLatin1String{"Drunken"},
        QLatin1String{"Dubby"},
        QLatin1String{"Elite"},
        QLatin1String{"Energetic"},
        QLatin1String{"Epic"},
        QLatin1String{"Ethereal"},
        QLatin1String{"Euphonic"},
        QLatin1String{"Even"},
        QLatin1String{"Eventual"},
        QLatin1String{"Expressive"},
        QLatin1String{"Extreme"},
        QLatin1String{"Exuberant"},
        QLatin1String{"Fading"},
        QLatin1String{"Familiar"},
        QLatin1String{"Fiery"},
        QLatin1String{"Filthy"},
        QLatin1String{"Fine"},
        QLatin1String{"Fleeting"},
        QLatin1String{"Flexible"},
        QLatin1String{"Floppy"},
        QLatin1String{"Fractal"},
        QLatin1String{"Fragile"},
        QLatin1String{"Fragrant"},
        QLatin1String{"Fresh"},
        QLatin1String{"Friendly"},
        QLatin1String{"Frugal"},
        QLatin1String{"Funky"},
        QLatin1String{"Galactic"},
        QLatin1String{"Gargantuan"},
        QLatin1String{"Gentle"},
        QLatin1String{"Gooey"},
        QLatin1String{"Greedy"},
        QLatin1String{"Grimy"},
        QLatin1String{"Grinding"},
        QLatin1String{"Gritty"},
        QLatin1String{"Groaning"},
        QLatin1String{"Growly"},
        QLatin1String{"Gusty"},
        QLatin1String{"Hairy"},
        QLatin1String{"Halting"},
        QLatin1String{"Happy"},
        QLatin1String{"Harmonious"},
        QLatin1String{"Haunting"},
        QLatin1String{"Hearty"},
        QLatin1String{"Honest"},
        QLatin1String{"Huge"},
        QLatin1String{"Humble"},
        QLatin1String{"Hungry"},
        QLatin1String{"Incomprehensible"},
        QLatin1String{"Increasing"},
        QLatin1String{"Jazzed"},
        QLatin1String{"Joyous"},
        QLatin1String{"Juicy"},
        QLatin1String{"Jumpy"},
        QLatin1String{"Leading"},
        QLatin1String{"Leashed"},
        QLatin1String{"Lilting"},
        QLatin1String{"Lingering"},
        QLatin1String{"Lonely"},
        QLatin1String{"Loose"},
        QLatin1String{"Loud"},
        QLatin1String{"Low"},
        QLatin1String{"Lucid"},
        QLatin1String{"Lurid"},
        QLatin1String{"Manic"},
        QLatin1String{"Melancholic"},
        QLatin1String{"Mellow"},
        QLatin1String{"Melodic"},
        QLatin1String{"Melodious"},
        QLatin1String{"Messy"},
        QLatin1String{"Minimal"},
        QLatin1String{"Modulated"},
        QLatin1String{"Moving"},
        QLatin1String{"Muddy"},
        QLatin1String{"Narrow"},
        QLatin1String{"Nasal"},
        QLatin1String{"Natural"},
        QLatin1String{"Neutered"},
        QLatin1String{"Neutral"},
        QLatin1String{"Niche"},
        QLatin1String{"Noble"},
        QLatin1String{"Nosy"},
        QLatin1String{"Noisy"},
        QLatin1String{"Obnoxious"},
        QLatin1String{"Obtuse"},
        QLatin1String{"Ornate"},
        QLatin1String{"Palid"},
        QLatin1String{"Peaky"},
        QLatin1String{"Pitchy"},
        QLatin1String{"Pithy"},
        QLatin1String{"Plinky"},
        QLatin1String{"Polite"},
        QLatin1String{"Prancing"},
        QLatin1String{"Precious"},
        QLatin1String{"Prideful"},
        QLatin1String{"Probing"},
        QLatin1String{"Professional"},
        QLatin1String{"Proper"},
        QLatin1String{"Quiet"},
        QLatin1String{"Raspy"},
        QLatin1String{"Restrained"},
        QLatin1String{"Rhapsodic"},
        QLatin1String{"Rhythmic"},
        QLatin1String{"Rich"},
        QLatin1String{"Ridiculous"},
        QLatin1String{"Rocky"},
        QLatin1String{"Rolling"},
        QLatin1String{"Roomy"},
        QLatin1String{"Rotten"},
        QLatin1String{"Rough"},
        QLatin1String{"Rubato"},
        QLatin1String{"Rumbling"},
        QLatin1String{"Sad"},
        QLatin1String{"Serious"},
        QLatin1String{"Shining"},
        QLatin1String{"Silent"},
        QLatin1String{"Sharp"},
        QLatin1String{"Slamming"},
        QLatin1String{"Slapping"},
        QLatin1String{"Sleepy"},
        QLatin1String{"Small"},
        QLatin1String{"Smooth"},
        QLatin1String{"Snappy"},
        QLatin1String{"Soft"},
        QLatin1String{"Soulful"},
        QLatin1String{"Spacious"},
        QLatin1String{"Spicy"},
        QLatin1String{"Staggering"},
        QLatin1String{"Steady"},
        QLatin1String{"Stellar"},
        QLatin1String{"Stinky"},
        QLatin1String{"Stormy"},
        QLatin1String{"Stumbling"},
        QLatin1String{"Sulking"},
        QLatin1String{"Sultry"},
        QLatin1String{"Sweet"},
        QLatin1String{"Swelling"},
        QLatin1String{"Tatty"},
        QLatin1String{"Temporary"},
        QLatin1String{"Tempting"},
        QLatin1String{"Tense"},
        QLatin1String{"Thick"},
        QLatin1String{"Tight"},
        QLatin1String{"Tinny"},
        QLatin1String{"Tonal"},
        QLatin1String{"Toxic"},
        QLatin1String{"Tranquil"},
        QLatin1String{"Translucent"},
        QLatin1String{"Tricky"},
        QLatin1String{"Trippy"},
        QLatin1String{"Twangy"},
        QLatin1String{"Uneven"},
        QLatin1String{"Unreal"},
        QLatin1String{"Unsafe"},
        QLatin1String{"Urgent"},
        QLatin1String{"Used"},
        QLatin1String{"Vibrating"},
        QLatin1String{"Wailing"},
        QLatin1String{"Warm"},
        QLatin1String{"Weird"},
        QLatin1String{"Wide"},
        QLatin1String{"Wicked"},
        QLatin1String{"Winking"},
        QLatin1String{"Wise"},
        QLatin1String{"Wonky"},
        QLatin1String{"Yielding"},
        QLatin1String{"Zoomy"},
    };
    const QStringList nouns{
        QLatin1String{"Absence"},
        QLatin1String{"Affect"},
        QLatin1String{"Anger"},
        QLatin1String{"Anvil"},
        QLatin1String{"Arpegio"},
        QLatin1String{"Bang"},
        QLatin1String{"Banger"},
        QLatin1String{"Bark"},
        QLatin1String{"Beauty"},
        QLatin1String{"Belch"},
        QLatin1String{"Bellow"},
        QLatin1String{"Blast"},
        QLatin1String{"Blip"},
        QLatin1String{"Bloom"},
        QLatin1String{"Bonanza"},
        QLatin1String{"Bounce"},
        QLatin1String{"Bridge"},
        QLatin1String{"Candy"},
        QLatin1String{"Chirp"},
        QLatin1String{"Clanger"},
        QLatin1String{"Clicker"},
        QLatin1String{"Club"},
        QLatin1String{"Clutter"},
        QLatin1String{"Color"},
        QLatin1String{"Comedy"},
        QLatin1String{"Communication"},
        QLatin1String{"Core"},
        QLatin1String{"Cut"},
        QLatin1String{"Damage"},
        QLatin1String{"Darkness"},
        QLatin1String{"Declaration"},
        QLatin1String{"Depth"},
        QLatin1String{"Diamond"},
        QLatin1String{"Dive"},
        QLatin1String{"Divination"},
        QLatin1String{"Doctrine"},
        QLatin1String{"Dream"},
        QLatin1String{"Drop"},
        QLatin1String{"Effect"},
        QLatin1String{"Equilibrium"},
        QLatin1String{"Escape"},
        QLatin1String{"Ether"},
        QLatin1String{"Explosion"},
        QLatin1String{"Expression"},
        QLatin1String{"Extract"},
        QLatin1String{"Extrapolation"},
        QLatin1String{"Farce"},
        QLatin1String{"Filigree"},
        QLatin1String{"Filth"},
        QLatin1String{"Flame"},
        QLatin1String{"Flight"},
        QLatin1String{"Flood"},
        QLatin1String{"Flower"},
        QLatin1String{"Friend"},
        QLatin1String{"Funk"},
        QLatin1String{"Garnish"},
        QLatin1String{"Gem"},
        QLatin1String{"Grind"},
        QLatin1String{"Growl"},
        QLatin1String{"Gyration"},
        QLatin1String{"Hammer"},
        QLatin1String{"Havoc"},
        QLatin1String{"Health"},
        QLatin1String{"Heap"},
        QLatin1String{"Heuristic"},
        QLatin1String{"Hiss"},
        QLatin1String{"Hook"},
        QLatin1String{"Hunch"},
        QLatin1String{"Hustle"},
        QLatin1String{"Increment"},
        QLatin1String{"Interlude"},
        QLatin1String{"Joke"},
        QLatin1String{"Journey"},
        QLatin1String{"Lance"},
        QLatin1String{"Lick"},
        QLatin1String{"Light"},
        QLatin1String{"Lilt"},
        QLatin1String{"Locus"},
        QLatin1String{"Mashup"},
        QLatin1String{"Maze"},
        QLatin1String{"Melancholy"},
        QLatin1String{"Melody"},
        QLatin1String{"Mesh"},
        QLatin1String{"Modulation"},
        QLatin1String{"Motif"},
        QLatin1String{"Mural"},
        QLatin1String{"Peak"},
        QLatin1String{"Potato"},
        QLatin1String{"Prelude"},
        QLatin1String{"Presence"},
        QLatin1String{"Procession"},
        QLatin1String{"Product"},
        QLatin1String{"Progression"},
        QLatin1String{"Quack"},
        QLatin1String{"Raspberry"},
        QLatin1String{"Release"},
        QLatin1String{"Response"},
        QLatin1String{"Rhapsody"},
        QLatin1String{"Riddle"},
        QLatin1String{"Ride"},
        QLatin1String{"Ringer"},
        QLatin1String{"Riser"},
        QLatin1String{"Roller"},
        QLatin1String{"Sadness"},
        QLatin1String{"Scale"},
        QLatin1String{"Scream"},
        QLatin1String{"Shimmer"},
        QLatin1String{"Silence"},
        QLatin1String{"Slice"},
        QLatin1String{"Soul"},
        QLatin1String{"Spray"},
        QLatin1String{"Squeak"},
        QLatin1String{"Squelch"},
        QLatin1String{"Stab"},
        QLatin1String{"Stack"},
        QLatin1String{"Stank"},
        QLatin1String{"Step"},
        QLatin1String{"Stream"},
        QLatin1String{"Strike"},
        QLatin1String{"Structure"},
        QLatin1String{"Strut"},
        QLatin1String{"Sunshine"},
        QLatin1String{"Swell"},
        QLatin1String{"Tension"},
        QLatin1String{"Thought"},
        QLatin1String{"Thud"},
        QLatin1String{"Tinkle"},
        QLatin1String{"Toot"},
        QLatin1String{"Tones"},
        QLatin1String{"Transmission"},
        QLatin1String{"Twang"},
        QLatin1String{"Valley"},
        QLatin1String{"Vapor"},
        QLatin1String{"Violence"},
        QLatin1String{"Vision"},
        QLatin1String{"Voice"},
        QLatin1String{"Wail"},
        QLatin1String{"Water"},
        QLatin1String{"Warcry"},
        QLatin1String{"Wave"},
        QLatin1String{"Whiff"},
        QLatin1String{"Whine"},
        QLatin1String{"Wreck"},

        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
        // QLatin1String{""},
    };
};

AdjectiveNoun::AdjectiveNoun(QObject* parent)
    : QObject(parent)
    , d(new AdjectiveNounPrivate)
{
}

AdjectiveNoun::~AdjectiveNoun()
{
    delete d;
}

const QString & AdjectiveNoun::adjective() const
{
    return d->adjectives[QRandomGenerator::global()->bounded(d->adjectives.count())];
}

const QString & AdjectiveNoun::noun() const
{
    return d->nouns[QRandomGenerator::global()->bounded(d->nouns.count())];
}

QString AdjectiveNoun::adjectiveNoun() const
{
    return formatted(QLatin1String{"%1 %2"});
}

QString AdjectiveNoun::formatted(const QString& format) const
{
    return format.arg(adjective()).arg(noun());
}
